name: Deploy docs

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: make install

      - name: Build and deploy
        run: make deploy
